### ISSUE TITLE
Manual approval required for workflow run 11088980065: Deploying Branch ${ GITHUB_REF##*/ }  to Production

### ISSUE THREAD

**Issue by yahyagulshan** [expertscloud/terraform-control-tower#11]
Please review the Terraform plan and approve or deny the deployment to production

Workflow is pending manual review.
URL: https://api.github.com/expertscloud/terraform-control-tower/actions/runs/11088980065

Required approvers: [abaidgulshan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by abaidgulshan** [comment]
no

**Comment by yahyagulshan** [comment]
Request denied. Closing issue and failing workflow.
