### ISSUE TITLE
Manual approval required for workflow run 11165571210: Deploying Branch ${GITHUB_REF##*/}  to Production

### ISSUE THREAD

**Issue by yahyagulshan** [expertscloud/terraform-control-tower#16]
Please review the Terraform plan and approve or deny the deployment to production
Branch name: main
Triggered by: abaidgulshan

Workflow is pending manual review.
URL: https://api.github.com/expertscloud/terraform-control-tower/actions/runs/11165571210

Required approvers: [abaidgulshan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by abaidgulshan** [comment]
yes

**Comment by yahyagulshan** [comment]
All approvers have approved, continuing workflow and closing this issue.
